PLUGIN_NAME=        blocky-tfenby
PLUGIN_VERSION=     1.3
PLUGIN_COMMENT=     Blocky DNS ad-blocker plugin for OPNsense
PLUGIN_DEPENDS=     blocky-tfenby
PLUGIN_MAINTAINER=  opnsense@fenby.me

.include "../../Mk/plugins.mk"
