PLUGIN_NAME=        blocky-tfenby
PLUGIN_VERSION=     3.0
PLUGIN_REVISION=    1
PLUGIN_COMMENT=     Blocky DNS ad-blocker plugin for OPNsense
PLUGIN_DEPENDS=     blocky-tfenby
PLUGIN_MAINTAINER=  opnsense@fenby.me
PLUGIN_WWW=         https://github.com/0xERR0R/blocky

.include "../../Mk/plugins.mk"
