PLUGIN_NAME=        blocky-tfenby
PLUGIN_VERSION=     1.0
PLUGIN_COMMENT=     Blocky DNS ad-blocker plugin for OPNsense
PLUGIN_DEPENDS=     blocky
PLUGIN_MAINTAINER=  opnsense@fenby.me

.include "../../Mk/plugins.mk"
