#!/bin/sh

# PROVIDE: blocky
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name=blocky
rcvar=blocky_enable

load_rc_config ${name}

: ${blocky_enable:=NO}
: ${blocky_config:="/usr/local/etc/blocky/config.yml"}
: ${blocky_user:=}
: ${blocky_group:=}
: ${blocky_flags:=}

if [ -n "${blocky_user}" ] && [ -z "${blocky_group}" ]; then
	blocky_group=$(id -gn "${blocky_user}")
fi

logfile="/var/log/${name}.log"
pidfile="/var/run/${name}.pid"
blocky_path="/usr/local/sbin/blocky"

command="/usr/sbin/daemon"
procname="/usr/local/sbin/blocky"
command_args="-c -f -o ${logfile} -p ${pidfile} ${blocky_path} \
	-c ${blocky_config} ${blocky_flags}"

start_precmd="blocky_precmd"

blocky_precmd()
{
	install -o "${blocky_user:-root}" -g "${blocky_group:-wheel}" \
		-m 0600 /dev/null "${pidfile}"
}

run_rc_command "$1"
